### ISSUE TITLE
pattern not parsed and reports error

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie-perlregex#5]
the following pattern is correct, although it throws `A subtraction must be the last element in a character class.`

```
/^[ !#-[\]-~]*\z/
```

Example:

```php
var_dump(preg_match('/^[ !#-[\]-~]*\z/', $subject));
```

**Comment by roberthusak** [comment]
I fixed it for certain cases, such as the one provided. However, to become fully compatible in this manner with PCRE, we'd need to remove [character class subtraction](https://www.regular-expressions.info/charclasssubtract.html), because it's allowed in .NET but not in PCRE. E.g. `[a-z-[aeiuo]]` has different meaning in each of them - while in .NET it matches `b`, in PCRE it matches `-]`.

**Comment by jakubmisek** [comment]
thank you Robert!
